version: 2
jobs:
  build:
    docker:
      - image: node:16.10.0

    steps:
      - checkout

      - run:
          name: npm clear
          command: rm -rf node_modules && npm cache clear --force && npm cache clean --force

      - run:
          name: npm install
          command: npm install --legacy-peer-dep

      - run:
          name: Build
          command: npm run build-release-stage

